name: Node.js Package

permissions:
  id-token: write
  contents: read

on:
  release:
    types: [published]

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
      - name: Set Git Version
        id: set-git-version
        uses: actions/github-script@v3
        with:
          script: return context.ref.replace(/refs\/tags\//, '')
          result-encoding: string
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm run build          
      - run: npm version --new-version ${{steps.set-git-version.outputs.result}} --no-git-tag-version
      - run: npm publish
